### PR TITLE
feat: import root folder from tmuxinator

### PR DESCRIPTION
**Pull request by fpietka**
Seems config import was only importing `project_root` part.

Updated the tests to reflect that change.

### CODE REVIEW

**Comment by tony** [comment]
I think we may be in a better situation if tmuxp just loads tmuxinator configs natively, any opinion on that?

**Comment by tony** [comment]
Looks good. Any other tmuxinator compatibility stuff we could put in there?

**Comment by fpietka** [comment]
reading tmuxinator configuration natively would be a nice feature indeed (.

also it's worth mentioning few nice addition (although not compatibility issues):
- `~/.tmuxinator/` folder could be part of the path we're looking into by default
- yml/yaml extension could be omitted (but it could be not limited to import ;) )

**Comment by tony** [comment]
> yml/yaml extension could be omitted (but it could be not limited to import ;) )

as in, the file would still be ``yaml`` or ``yml``, but it wouldn't require typing the full filename to load it?

**Comment by fpietka** [comment]
yes, and more generally so we can type `tmuxp load myproject` to load `myproject.yaml`

**Comment by tony** [comment]
i like the idea

can you make an issue for it?

**Comment by fpietka** [comment]
done (#160)

**Pull request merged**
