### PR TITLE
Allow multiple configuration files on command line

### PR DESCRIPTION
**Pull request by madprog**
Fixes tony/tmuxp#133 as far as I'm concerned

I would like to write a test for this, but I haven't found any test example running the command line. Or did I miss it?

### CODE REVIEW

**Comment by tony** [comment]
I'm not certain if this wouldn't inadvertently cause other commands to break potentially. I'm willing to test and QA this thoroughly by hand if thats what required.

However, have you considered this:

```
tmuxp load ~/path/to/config.yaml -d && tmuxp load ~/path/to/config.json -d
```

You can optionally remote the ``-d`` if you would like to attach the last one automatically:

```
tmuxp load ~/path/to/config.yaml -d && tmuxp load ~/path/to/config.json
```

Does this achieve the affect you'd want?  IMO It may better to make the cli portion compatible with xargs so sessions could loaded in parallel.

**Comment by madprog** [comment]
Ok, I did not think about `-d`.

However, attaching to 2 or more sessions at the same time does not makes sense. So we could document that in absence of `-d`, only the session described by the *last* configuration file would be attached.
Or that, in the case of multiple files, `-d` is implied for all of them.
What do you think?

About compatibility with xargs, do you mean that the tmuxp would use xargs internally, or that a user could run tmuxp with xargs?
Because, in the second case, without a `-L`, `-n` or `-P 1` flag, it would just call tmuxp with multile arguments.

The worlaround I'm using for the moment is:

```shell
for conf in ~/.config/tmux/autorun.d/*.yaml; do
    tmuxp load -d $conf
done
```

**Comment by tony** [comment]
> About compatibility with xargs, do you mean that tmuxp would use xargs internally, or that a user could run tmuxp with xargs?

I also played around (while using ``-L`` and ``-n``) because seeking to make a one-liner out of it, however didn't get the result I intended. This leaves open the possibility for using a ``for`` loop.

> However, attaching to 2 or more sessions at the same time does not makes sense. So we could document that in absence of -d, only the session described by the last configuration file would be attached.

Definitely feel free to document and add *anything* that'd be helpful. Including ``-d``

However, current behavior in this PR (with the absence of ``-d``) will load the first session, and only continue loading the second config after the tmux client in that tty is detached.  However, conveniently, if the tmux session already exists, it will iterate through one by one and prompt them still.

So that leaves us with a bit of bikeshedding. I think we could by default do what you mentioned documenting, we would mark all but the last config as detached by default.

**Comment by tony** [comment]
Works for me.

Care to document the behavior of ``-d`` and loading multiple configs?

**Pull request merged**
