### PR TITLE
Fix Server.attached_sessions return type

### PR DESCRIPTION
**Pull request by thomasballinger**

### CODE REVIEW

**Comment by thomasballinger** [comment]
Server.attached_sessions was documented to return a tmux session object or None but was returning a list of session dicts or None.

**Comment by thomasballinger** [comment]
It's not clear to me what the right fix is (the note in the docs makes it sound like maybe the list will only every be length 1?) but was going to raise an issue and thought I'd take a whack at it instead.

**Comment by tony** [comment]
@thomasballinger Greetings!

 Nice, I'm taking a look!  Can you rebase this so the tests run? I want to be sure it doesn't cause any regressions on older tmux versions.

**Comment by tony** [comment]
I made a change at https://github.com/tony/tmuxp/commit/150fd9c9b921b4a941de71ed560ea1058a4073ad to fix travis tests.

**Comment by tony** [comment]
Nice @thomasballinger, you're becoming the tmuxp master

**Pull request merged**
